name: CI

on: [push]

jobs:
  test:
    name: check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up Python
        uses: actions/setup-python@v1
      - name: install and run black
        run: |
          pip install black
          black --check .
