name: CI

on: [push]

jobs:
  test:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      run: |
        pip install black
        black --check .
